
[window]
blur = true
opacity = 0.8
padding = { x = 10, y = 10 }
decorations ="full"

[env]
AUTO_TMUX = "1"
[font]
size = 14
normal = { family = "JetBrainsMono Nerd Font"}

[terminal]
osc52 = "CopyPaste"

[keyboard]
bindings = [
  { key = "J", mods = "Command", chars = "\u0001" },
]
